### ISSUE TITLE
Homepage content & layout

### ISSUE THREAD

**Issue by sinkinsona** [Sabytel-Web/sabytel#12]
@sinkinsona, @ahmedhussein, @Sabytel 
Here is what I propose for the Home Page
New Sabytel-Home Page

Top Image:  Welcome to Sabytel Technologies Inc.
Cyber and ICT Security services at its best 
or
Cyber and ICT Security is our main expertise

2nd Image (if any) Awareness of the risks and available safeguards is the first line of defense for the security of information systems and networks.

Sabytel – Where your security matters.

Middle of page – 4 images + text
4 areas of expertise

1.	Today’s business environment is changing and you need to change with it. A bigger Business to Business (B2B) internet presence would go a long way towards reducing your cost of doing business while increasing your bottom line and keeping you competitive. 
How can you securely increase your E-Business while every day, more and more major corporations are being hacked and penetrated by cybercriminals, corporate spies and dedicated hacktivists? How can you be more open to the electronic age while better protecting yourself at the same time?
You need to protect yourself and the right Information Security plan can help. Sabytel provides the experience, knowledge and tools you need to enable your business to process safely and securely while you expand your internet presence. 

2.	Security awareness is the knowledge and attitude members of an organization possess regarding the protection of the physical and information assets.

Being security aware means you understand that there is the potential for some people to deliberately or accidentally steal, damage, or misuse the data that is stored within your organizations’ computer systems. It is prudent to support the assets of the institution’s information, physical and personal, by stopping that from happening.

3.	Sabytel offers specialized IT security services that address your organization’s particular needs. 

Threat and Risk Assessments We conduct full IT threat and Risk Assessments providing recommendations for security improvements. 

Network Vulnerability Assessments We provide full network vulnerability assessments culminating in reports on identified vulnerabilities and step-by-step plans on how to eliminate them. 

Departmental Policies and Procedures We help you to develop policies and procedures to improve your IT network security. 

Business Resumption Plan (BRP) We assist you in developing procedures and schedule to test your BRP on an annual basis.  This will include documentation of critical business functions that need to be recovered in order for business operations to continue.

Certification and Accreditation: Conducts the full Certification and Accreditation activities ensuring successful certification and accreditation of your systems in accordance with defined national and international requirements.

4.	Corporate Strategy Solution will help your organization identify and address strategic issues 

Sabytel can help to improve your organization’s business operations by developing a Corporate Strategy Solution that will help your organization to identify and address strategic issues that are important to its success. As part of this solution, Sabytel will provide a two-part strategic analysis of your organization, including a Base Case Analysis of current operations, and a Strategy Formulation and Implementation plan to improve upon those operations. The Market Research Studies solution will provide you with reliable information that can be used to identify your organization’s market niche and develop effective business strategies

Also here is a quick mock up

[New Sabytel-Home Page mock up.docx](https://github.com/Sabytel-Web/sabytel/files/78882/New.Sabytel-Home.Page.mock.up.docx)

When I save the comment, the numbering of the 4 areas of expertise change.  Don't know why.  So just be aware.

layout: Corporate 3

**Comment by sinkinsona** [comment]
@SpecialKelsey moved the Homepage discussion to its own issue.

**Comment by sinkinsona** [comment]
@SpecialKelsey requested the following "Also, while you there, the Home Page in the top picture frame, it has the Sabytel Logo  and the wording says Welcome to Sabytel, basically you see Welcome to Sabytel Sabytel.  Can you remove the Sabytel in the Welcome to."

@sinkinsona adding @SpecialKelsey requests above to the appropriate Homepage issue.

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Layout = http://theme.stepofweb.com/Smarty/v1.1.2/HTML/index-corporate-3.html
Content = https://drive.google.com/open?id=0B95j4zfm5LiLTGRhaTVtbDZITTg
Content = https://drive.google.com/open?id=0B95j4zfm5LiLZVpGbzJpclo5RDg 
for Banner Picture of Sabytel
Content = https://drive.google.com/open?id=0B95j4zfm5LiLRDdObTNRSWVzOEE 
for Feature Pictures Only
Content = https://drive.google.com/open?id=0B95j4zfm5LiLSUdTWjh6cG0wN0E
for Banner Picture only
Mock Up = https://drive.google.com/open?id=0B95j4zfm5LiLUm0tbVNFN2VrMjg

**Comment by sinkinsona** [comment]
@SpecialKelsey This issue is difficult to understand - Could you create 1 issue for homepage banner + the text for each banner and create a second issue for Homepage features section + the text for each feature.

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Layout =http://theme.stepofweb.com/Smarty/v1.1.2/HTML/index-corporate-3.html
Content = https://drive.google.com/open?id=0B95j4zfm5LiLeHB1WXlXYTVvNEk
COntent = https://drive.google.com/open?id=0B95j4zfm5LiLZVpGbzJpclo5RDg  (banner picture of Sabytel only)
Content = https://drive.google.com/open?id=0B95j4zfm5LiLSUdTWjh6cG0wN0E (for banner pictures only)  Except or the Sabytel Logo banner picture, there is no text to add to the pictures.  I think the image says it all.

**Comment by SpecialKelsey** [comment]
@Sabytel 
Hi Nabil.  Can I get your approval on not adding text to the 3 banner pictures of the Landing Page.  The one with your Company logo will have text but the others I believe speak for themselves.

**Comment by sinkinsona** [comment]
Content = https://drive.google.com/open?id=0B95j4zfm5LiLeHB1WXlXYTVvNEk
