### ISSUE TITLE
reduce repo size

### ISSUE THREAD

**Issue by sinkinsona** [Sabytel-Web/sabytel#15]
Remove many of the assets not used to reduce the size of the sabytel repository

**Comment by sinkinsona** [comment]
@ahmedhussein - I just submitted a commit to reduce the size of the repo.  Many of the resource were many mb in size and not needed.  Please make sure to grab the latest copy - thanks

**Comment by ahmedhussein** [comment]
will the sync in the github desktop client do it?

**Comment by sinkinsona** [comment]
I do not use a client but cmd line.  The sync sounds like it would do it.  You should notice 900+ less files mostly in assets/images.  To confirm check assets/images/demo  you should not see the video folder as I deleted it as it contained many MB of videos that we will not need.
