### ISSUE TITLE
What We Can Do For You - Layout & content

### ISSUE THREAD

**Issue by sinkinsona** [Sabytel-Web/sabytel#17]
Layout = page-about-us-5.html
Content Link = https://docs.google.com/document/d/15U4VKvn5jACaDuLRPc9Ima93Nci8a3Yr9TeQDTOTxpg/edit?usp=sharing_eid&ts=56828ce5

**Comment by sinkinsona** [comment]
Please confirm once content is final and just make sure the issue has the correct link and assign it to me.

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Layout = http://theme.stepofweb.com/Smarty/v1.1.2/HTML/index-corporate-3.html
Under the About Us like on the Sabytel demo site
Content = https://drive.google.com/open?id=0B95j4zfm5LiLQUd0VmJDSXpEMm8

**Comment by sinkinsona** [comment]
@SpecialKelsey as discussed for this one we will not use the same layout as the homepage as I site should only have the main page with the large slideshow.  I put up an initial version for your review and feedback.
http://sabytel.com/demo/what-we-can-do.php

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Hi Andrew,

Good job.  I think we have a winner.

**Comment by sinkinsona** [comment]
content review and approved so closing this issue
