### ISSUE TITLE
You Need us - Content & layout

### ISSUE THREAD

**Issue by sinkinsona** [Sabytel-Web/sabytel#18]
Layout = 
Content Link = https://docs.google.com/document/d/1pf9fmciDdHd71n4pX4QUZQ0mrN03kexUOQVmxDPaAn4/edit?usp=sharing_eid&ts=56828ce5

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Layout = http://theme.stepofweb.com/Smarty/v1.1.2/HTML/index-corporate-3.html 
under the About Menu like on the Sabytel Demo site and also 
Layout = http://theme.stepofweb.com/Smarty/v1.1.2/HTML/page-services-2.html 
bottom part of the page
Content = https://drive.google.com/open?id=0B95j4zfm5LiLRHNoclJsVzdhbG8
Mock Up = https://drive.google.com/open?id=0B95j4zfm5LiLajUyYUZQNUVMZkE

**Comment by sinkinsona** [comment]
@SpecialKelsey can you confirm the layout & content to use - it looks like you want a hybrid of corporate3 & service2.  Maybe upload a screenshot if possible

**Comment by SpecialKelsey** [comment]
@sinkinsona  - Sorry about that
Layout = http://theme.stepofweb.com/Smarty/v1.1.2/HTML/page-services-2.html 
 bottom part of the page
 Content = https://drive.google.com/open?id=0B95j4zfm5LiLRHNoclJsVzdhbG8
 Content = https://drive.google.com/open?id=1Jtfo4rtSpdjoGLbwFBy9ixAJZITMPBYeY2ba6U-TIfg
 Mock Up = https://drive.google.com/open?id=0B95j4zfm5LiLajUyYUZQNUVMZkE

**Comment by sinkinsona** [comment]
@SpecialKelsey here is the first past at implementing the mock up / content for the you need us page. http://sabytel.com/demo/you-need-us.php

Have a look and provide me with your feedback - thx

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Hi Andrew,

It looks really nice.  I like it.  The only point would be the 'After implementation, Just Before Rollout'.  Is it possible to move the sentence 'Just Before rollout' on the same line as rollout.  The word rollout looks off being the only word there under the image.  It would even it out a little.  Did you want me to pick the icons to go with the text.  I'll choose from what is offered on Smarty.  Let me know

**Comment by sinkinsona** [comment]
@SpecialKelsey have made the requested changes - go ahead and select the icons that you would like to use for this page

**Comment by sinkinsona** [comment]
icons have been implemented so closing this issue
