### ISSUE TITLE
Cyber and ICT Security - content & layouts

### ISSUE THREAD

**Issue by sinkinsona** [Sabytel-Web/sabytel#19]
Layout = page-services-2.html
Content Link = https://docs.google.com/document/d/1gUREYnUnn1RNGApFRulRHSY04ntc0tBS_ZGoNFPqGno/edit?ts=56828ce5

**Comment by sinkinsona** [comment]
![image](https://cloud.githubusercontent.com/assets/1258144/12159147/e927c08a-b4ad-11e5-836d-9b9f9cba94c9.png)

**Comment by sinkinsona** [comment]
assigning it back to you as it looks like you are still finalizing content.  Once content is final just provide me with link to the document and assign it back to me.  thx

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Layout = http://theme.stepofweb.com/Smarty/v1.1.2/HTML/page-services-2.html
Content Link = https://drive.google.com/open?id=0B95j4zfm5LiLME94R3IxMWxqVjQ
Mock up = https://drive.google.com/open?id=0B95j4zfm5LiLajUyYUZQNUVMZkE

**Comment by sinkinsona** [comment]
@SpecialKelsey still a work in progress but let me know what you think.
http://sabytel.com/demo/cyber-ict-security.php
I changed it up a little from the mock up so that we did not have 2 pages that looked the same.  Let me know

**Comment by sinkinsona** [comment]
closing this issue as it is being discussed in issue #50
