### ISSUE TITLE
Select layouts for the Sabytel site

### ISSUE THREAD

**Issue by sinkinsona** [Sabytel-Web/sabytel#2]
@SpecialKelsey review the sample theme and select the layouts that we would like to use for the new site.  http://theme.stepofweb.com/Smarty/v1.1.2/HTML/start.html

I think for the homepage we are going to use Corporate 3

**Comment by Sabytel** [comment]
I kind like Corporate 3 as well.

Ahmed, is your images will work good with Corporate 3?

Nabil

**Comment by SpecialKelsey** [comment]
@Sabytel 
We need to decide also on the layouts for the About Us, Services, Contact and Careers.  This will help me define the top menu and the links to the new menus

These are my preferences:
For About Us:  Layout 5
Services:  Layout 2
Contact:  Layout 2 or 3
Careers:  No choices.

**Comment by ahmedhussein** [comment]
I'd Agree with all the choices, for the contacts, I'd say no need for the wide sized map as long as the user can click on it for a further action

The images will look great when we combine them with the animated text. super great

**Comment by SpecialKelsey** [comment]
Thanks for the input.  I didn’t like the map either but you can fix that. 

 

Elise Kelsey 

Client Relationship Manager / Gestionnaire des relations clients

Sabytel Technologies Inc.

613-299-3459



 <http://www.sabytel.com/> www.sabytel.com

 <http://www.sabytel.com/> www.niskaa.com

**Comment by ahmedhussein** [comment]
The smaller map looks nice even on phones.

**Comment by sinkinsona** [comment]
created separate issues for this
