### ISSUE TITLE
Physical TRA - Content & layout

### ISSUE THREAD

**Issue by sinkinsona** [Sabytel-Web/sabytel#20]
Layout = 
Content Link =

**Comment by sinkinsona** [comment]
@Sabytel @SpecialKelsey please collaborate on this one

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Layout=http://theme.stepofweb.com/Smarty/v1.1.2/HTML/portfolio-single-parallax.html
Content= https://docs.google.com/document/d/1H0qFfhe9Nsn0pt-a4wprYp57IY9MoTa0zrL7dri8vLw/edit?usp=sharing

I would see this on the top of the page and the other Physical Security (Altel) on the bottom part of the page.  Comments, Suggestions.

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Not sure we still need this issue.  See issue 21.  All the Physical Security is on one page.  The slider images at the bottom of the page are for the Altel Security only.
Layout = http://theme.stepofweb.com/Smarty/v1.1.2/HTML/portfolio-single-parallax.html
Content = https://drive.google.com/open?id=0B95j4zfm5LiLNTZaNEJkVTJOSGM
I don't have all the slider images yet.  Once I have them, I will add them.

**Comment by sinkinsona** [comment]
@SpecialKelsey can you confirm if this issue can be closed?

**Comment by SpecialKelsey** [comment]
@sinkinsona 
If you have everything you need in issue 21 then close this one.

**Comment by sinkinsona** [comment]
Closing as @SpecialKelsey has confirmed that it is superseded by Issue #21
