### ISSUE TITLE
Cyber/ITServices - Layout and content

### ISSUE THREAD

**Issue by SpecialKelsey** [Sabytel-Web/sabytel#23]
@Sabytel-Web/sabytel_team
 Layout:
Content:  
[New Proposed IT Security Services Pages.docx](https://github.com/Sabytel-Web/sabytel/files/86436/New.Proposed.IT.Security.Services.Pages.docx)

Since the Physical Security will have it's own menu item, here is what I propose for the Cyber/IT Security page. This would mean that the You Need Us would not be in the About Us. I think this new page actually works better together.  Comments, suggestions, feedback.

**Comment by sinkinsona** [comment]
Looks good to me but will let @Sabytel make the call.  If the change is accepted please close https://github.com/Sabytel-Web/sabytel/issues/18 (You need us content) and if it require modification to the nav bar re-open https://github.com/Sabytel-Web/sabytel/issues/10 to describe the modifications.

**Comment by Sabytel** [comment]
yes it looks good, I like it. I just need to take the time to confirm content hopefully this week.
Nabil
