### ISSUE TITLE
Career - Content

### ISSUE THREAD

**Issue by SpecialKelsey** [Sabytel-Web/sabytel#24]
@sinkinsona 

Hi Andrew,
Please reduce the font size of Benjamin Disraeli next to the quote.  About half the size of the font that is currently there.

**Comment by sinkinsona** [comment]
@SpecialKelsey made this fix - should be good.  If you want other changes just re-open

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Nabil wants to change the Success is the child of audacity to

Creative and critical thinking is our revenue-Nabil Aly

**Comment by sinkinsona** [comment]
added the fix - re-open if other changes are required
