### ISSUE TITLE
Menu Header - Layout

### ISSUE THREAD

**Issue by SpecialKelsey** [Sabytel-Web/sabytel#26]
@Sabytel-Web/sabytel_team 

Menu Header = http://theme.stepofweb.com/Smarty/v1.1.2/HTML/feature-header-transparent-line.html

This is for the 'Home' page.  That way the whole Sabytel Logo would show better

**Comment by sinkinsona** [comment]
Just want to confirm that you would like the transparent header on the homepage only?  Just need to add this <div id="header" class="sticky  header-md transparent clearfix"> to the header div on the index.php file.

**Comment by ahmedhussein** [comment]
Good Morning Andrew,

As far as I remember, it wasn't transparent at the homepage. Sorry for being away as my surface is still in service.

Best Regards,

Ahmed Hussein
613-854-4944

**Comment by SpecialKelsey** [comment]
@Sabytel-Web/sabytel_team 

Good morning,

Yes this would be on the homepage only.

**Comment by sinkinsona** [comment]
deferred for now
