### ISSUE TITLE
Upload sample homepage images

### ISSUE THREAD

**Issue by sinkinsona** [Sabytel-Web/sabytel#27]
@Sabytel-Web/sabytel_team  I have uploaded some of the requested sample images to the demo site.

http://sabytel.com/demo/

Have a look and let me know which one to keep and or replace

**Comment by SpecialKelsey** [comment]
@Sabytel-Web/sabytel_team  I like all of them.  I don't think we will need any text to be displayed as they scroll.  I think they convey the message.  The only change would be the Sabytel one.  I would remove the Welcome to Sabytel and just leave at Welcome. Il will open the appropriate issues when the time comes to upload the real thing. If everyone agrees Amhed will now be able to purchase those from Adobe so we don't have the watermark.

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Hi Andrew.  Here are the Final Sabytel Images for the Landing Page
https://drive.google.com/file/d/0B95j4zfm5LiLSUdTWjh6cG0wN0E/view?usp=sharing
https://drive.google.com/file/d/0B95j4zfm5LiLZVpGbzJpclo5RDg/view?usp=sharing
[Final-Sabytel Landing Page Images.docx](https://github.com/Sabytel-Web/sabytel/files/184364/Final-Sabytel.Landing.Page.Images.docx)
[Final-New Sabytel Logo Banner page.docx](https://github.com/Sabytel-Web/sabytel/files/184365/Final-New.Sabytel.Logo.Banner.page.docx)

**Comment by sinkinsona** [comment]
I have added the sample images and they will be included in next version that will be pushed to the demo  site
