### ISSUE TITLE
About Us - Content and Layout

### ISSUE THREAD

**Issue by SpecialKelsey** [Sabytel-Web/sabytel#28]
@sinkinsona 
Layout = http://theme.stepofweb.com/Smarty/v1.1.2/HTML/page-about-us-5.html
Content = https://drive.google.com/open?id=1VU4wGsKK1yU1u8E98DBxFLHHhOpOotWx8YAFFjwlfMQ
Mock up = https://drive.google.com/open?id=0B95j4zfm5LiLZ3Nqd1A2cFAxWkk #

**Comment by sinkinsona** [comment]
@SpecialKelsey I added the About Us page http://sabytel.com/demo/about-us.php for your review.  I am not adding the images as waiting for them to be created.

**Comment by sinkinsona** [comment]
@SpecialKelsey if the content is good close this issue - we have a separate issues to add images required

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Another change to the text on the bottom of the page - Why Choose Us

https://drive.google.com/open?id=0B95j4zfm5LiLc1NXSEdxMU1jalk

**Comment by sinkinsona** [comment]
The google doc refers to adding text to the careers page so I implemented that change.  If changes are required to the about us page specify what they are and re-open issue

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Sorry about that.  Here is the link to the document
https://drive.google.com/file/d/0B95j4zfm5LiLRE9VWnhVYXR5T00/view?usp=sharing

**Comment by sinkinsona** [comment]
Implemented the requested changes - re-open if other changes are required
