### ISSUE TITLE
Content and Layout Home Page - Features Only 

### ISSUE THREAD

**Issue by SpecialKelsey** [Sabytel-Web/sabytel#29]
@sinkinsona 
Layout =
Content = https://drive.google.com/open?id=0B95j4zfm5LiLcXhKTzhZam9ZSFU
Content pictures only = https://drive.google.com/open?id=0B95j4zfm5LiLRDdObTNRSWVzOEE

**Comment by sinkinsona** [comment]
@SpecialKelsey Still a work in progress but let me know what you think of the features.  I think the feature images should be wider and not as height + we might need to trim some text.
http://sabytel.com/demo/

**Comment by SpecialKelsey** [comment]
@sinkinsona 
I like it and I think it's a good compromise.  I agree with what you're saying for the height and width.  Is it possible to slow down the transition.  Noticed also that the little arrow < > block out some of the text. Let me know what can be done about that.  Thanks for the great work.

**Comment by sinkinsona** [comment]
@SpecialKelsey For now I have just used one image as I will need to ask Ahmed to create some for the new height & width.  I slowed down the transition speed and moved the arrows up so they do not block out the text.  The only thing I think we need to do is balance the amount of text that we have per feature.  Some we have a lot and other only 1 paragraph so it creates white space.  Let me now what you think.

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Content = https://drive.google.com/open?id=0B95j4zfm5LiLcUlHR0FzVjBaa0U
Best I could do.

**Comment by sinkinsona** [comment]
I have added the modified text and it looks good - If you are ok with the changes lets close this issue.  We should open a new issue to address the feature images - we need some that are 560 width x 281 height (height can be smaller as well)

**Comment by SpecialKelsey** [comment]
@sinkinsona 
It looks much better.  One little thing,  The text Corporate Business Solution has a colon ( : ) and should not.  Just a minor typo.  
You can then close this issue.

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Can't reopen so here are the changes.
[ISO Information Security Management Systems Only - Revised 2016-08-25.docx](https://github.com/Sabytel-Web/sabytel/files/437659/ISO.Information.Security.Management.Systems.Only.-.Revised.2016-08-25.docx)
[Cyber Security Advisory and Project Management Services Only Revised 2016-08-25.docx](https://github.com/Sabytel-Web/sabytel/files/437658/Cyber.Security.Advisory.and.Project.Management.Services.Only.Revised.2016-08-25.docx)

Google Docs under the new folder Revised Sabytel Website Docs-2016-08-25

https://drive.google.com/open?id=0B95j4zfm5LiLZ2E5M3ZtamQxX28
https://drive.google.com/open?id=0B95j4zfm5LiLamllMnlQVDl6bk0

**Comment by sinkinsona** [comment]
Implemented fixe - reopen if other issues

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Another change requested by Nabil.  For the Information Management.... wants the title changed from the existing to ISO 27001:2013 ISMS Implementation & Auditing

https://drive.google.com/file/d/0B95j4zfm5LiLYldWS3hBWmxEalk/view?usp=sharing

**Comment by sinkinsona** [comment]
Added the request change - if other changes are required **re-open issue** and let me know what needs further changes

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Sorry Andrew but I don't have any access to re-open issues.  The text is not formatted properly and there is code showing in the title.  Please fix.

**Comment by sinkinsona** [comment]
I will get that fixed

**Comment by sinkinsona** [comment]
should be good now
