### ISSUE TITLE
Website page design - Keep in Touch Newletter Sign Up

### ISSUE THREAD

**Issue by SpecialKelsey** [Sabytel-Web/sabytel#32]
@Sabytel-Web/sabytel_team 

I think we should remove the Keep in Touch - Sign up for our newsletter on the bottom port of the pages  of the website.  We don't have a newsletter unless someone has an idea what we can use that space for.

**Comment by sinkinsona** [comment]
My recommendation would be to keep it as all it really does is keep a list of emails that are interested in our services / info.  We do not have to create a news letter but can simply email those that signed up offers such as upcoming Iso training in Ottawa or other stuff.  Let me know if we keep or get rid of it - Thanks

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Good idea.  Let me check with the boss and see what he thinks.

**Comment by sinkinsona** [comment]
closing for now
