### ISSUE TITLE
social media account setup

### ISSUE THREAD

**Issue by sinkinsona** [Sabytel-Web/sabytel#39]
create Sabytel accounts for social media (twitter, facebook, etc)...
![screen shot 2016-04-27 at 6 01 36 pm](https://cloud.githubusercontent.com/assets/1258144/14869579/4b1d0c86-0ca2-11e6-834d-dbe55bee3163.png)

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Let me check with Nabil on that.  I don't have time to do the social media stuff.

**Comment by SpecialKelsey** [comment]
@sinkinsona 
For now keep Facebook, Twitter and LinkedIn.

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Here is the answer from Nabil
Hi Andrew,
Here is the information for Sabytel Social media, they are not published yet, please publish them.  I recommend that we use only Twitter and LinkedIn only.

1)    Facebook userID: Aly@sabytel.com  /PWD: Sabytel2014
2)    Twitter(@Sabytel)  userID: info@sabytel.com   /PWD: Sabytel2014 
3)      I do not remember if we had a LinkedIn account for Sabytel technologies, please create one under info@sabytel.com .

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Hi Andrew,

The LinkedIn account is linked through Nabil's own private LinkedIn profile.  It's the only way to have a company page.  Let me know what you need to be able to connect that to our webpage.  My profile also has Administrator rights to the company profile page.

**Comment by sinkinsona** [comment]
Modified linkedin as request and removed facebook till we have an account created
