### ISSUE TITLE
Trying to upload some background files

### ISSUE THREAD

**Issue by ahmedhussein** [Sabytel-Web/sabytel#4]
Hi Andrew, Are you going to upload the files here or should I?

**Comment by sinkinsona** [comment]
If you have some pages with the images you are working on go ahead and uploaded them.

**Comment by ahmedhussein** [comment]
So, You can see the folder I recently uploaded?

**Comment by sinkinsona** [comment]
No I am not seeing the new files.   Did you do a git add and then a git commit? Let me know if you want me to give you a hand with this.

**Comment by ahmedhussein** [comment]
I'm using github for desktop and it's getting me confused
For sure I'd love to :)

**Comment by sinkinsona** [comment]
@ahmedhussein just uploaded the initial files for the site.  Let me know if you would like to Skype so that I can help with github.

**Comment by sinkinsona** [comment]
I have now given you write access to the sabytel repository.  Make sure that you use git pull to ensure you keep your work up to date with changes I am making.  Let me know if you have any questions or need any help.
