### ISSUE TITLE
Images homepage slider

### ISSUE THREAD

**Issue by sinkinsona** [Sabytel-Web/sabytel#40]
Create and drag and drop into this issue homepage slider images
http://sabytel.com/demo/

**Comment by SpecialKelsey** [comment]
@sinkinsona 
AdobeStock_84927851.jpeg
AdobeStock_94386906.jpeg
volumetric_03_V2.png
Ahmed is looking for the other image.

**Comment by sinkinsona** [comment]
Added the slider images - Let me know if you are good with them

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Three of them are good.  I'm waiting again on Ahmed for another one he needs to purchase  as we are using the same image twice (slider and What we can do for you-Adobe 95169113.) 
So the images for the Slider are now
AdobeStock_84927851.jpeg
AdobeStock_94386906.jpeg
volumetric_03_V2.png
and a new to be purchased - AdobeStock91315151 or Adobe Stock 94644195
Almost done.

**Comment by sinkinsona** [comment]
changes the image for what we can do - let me know what you think

**Comment by SpecialKelsey** [comment]
@sinkinsona 
All good for the What we can do.  Still waiting on Ahmed for the other image.  Don't like that we have 2 of them referring to Data on the banner images.  I was wondering if these images can be updated fairly easily after we go live.  We can work with what we have for now and change them later.  Please advise.

**Comment by sinkinsona** [comment]
yes - If we do not receive the new images soon we can simply replace the ones we have after we are live.

**Comment by SpecialKelsey** [comment]
@sinkinsona

**Comment by sinkinsona** [comment]
I have uploaded the requested images - have a look and let me know what you think

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Sorry, I guess I should have mentioned that I still wanted the Sabytel logo one also.

**Comment by SpecialKelsey** [comment]
Hi Andrew,

 

My bad.  I wanted those four images plus the Sabytel logo that we had before.  Also, the one with the lightbulb, the resolution is not very good.  Don’t know if it has to do with the size of the image.  

 

As for the carousel ones, we go with what we have for now.  We update later is needed.

 

Elise Kelsey 

Client Relationship Manager / Gestionnaire des relations clients

Email :  <mailto:elise@sabytel.com> elise@sabytel.com

Web :  <http://www.sabytel.com/> www.sabytel.com 

 

Tel : 613-299-3459

Sabytel :  613-235-9999

Fax : 343-887-9388

**Comment by sinkinsona** [comment]
Have a look at the hp slider images and let me know what you think

**Comment by sinkinsona** [comment]
Still need to do some work here as it takes to long to load in mobile + not sized properly.  Will be looking into this

**Comment by SpecialKelsey** [comment]
@sinkinsona 
The resolution is much better but not fond of the black around it.

**Comment by sinkinsona** [comment]
@SpecialKelsey @Sabytel Here is a new version that works in all devices a have tested and loads quickly.  http://sabytel.com/demo/index2.php  Also thought that fullscreen mode was taking up a lot of room so went with full width instead.  Let me know what you think

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Hi Andrew,  It looks good.  If it works on all devices, it's a go.
