### ISSUE TITLE
Images homepage carousel

### ISSUE THREAD

**Issue by sinkinsona** [Sabytel-Web/sabytel#41]
Create and drag and drop into this issue homepage carousel images

**Comment by SpecialKelsey** [comment]
@sinkinsona 
For Cyber Security= not purchased yet
For Business Solution= Comm01.png
For Personal – Onsite resources= GlassBuildings.png
For Information Security Management= AdobeStock_100228251.jpeg
For ISO Training= Branding Identity MockUp 5.png

**Comment by sinkinsona** [comment]
I have added these images - let me know what you think.  I went and created one to Cyber Security and chose a different one for Comm01.png as it was to narrow

**Comment by SpecialKelsey** [comment]
@sinkinsona 
If the Comm01@2x.png from Ahmed One drive was too small, then keep what you have.  Again if there are royalties, we need to purchase it.  I asked Ahmed to rework the ISO training image as I find it does not look very good.  If he takes too long, then we use what we have.  Hope to have an answer from him tomorrow.

**Comment by sinkinsona** [comment]
Added new images that we are free to use - let me know what you think

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Ahmed sent us the reworked images.  I sent an email to confirm the one I would like and the size.  Please confirm with him via email, for the size required.

**Comment by sinkinsona** [comment]
add this image

![unnamed](https://cloud.githubusercontent.com/assets/1258144/18875314/48c0628a-8493-11e6-9b52-7bb574b3d32b.jpg)

**Comment by sinkinsona** [comment]
@SpecialKelsey Is it possible to get this image more horizontal to fit the hp carousel or do we use the one we have ?

**Comment by SpecialKelsey** [comment]
@sinkinsona 
I sent an email yesterday to you and Ahmed asking him that he resize this one (565x269).  You need to confirm with him the size required.  Again if this will delay the go live, we go with what we have for now and update later

**Comment by sinkinsona** [comment]
confirming size is  (565x269)

**Comment by sinkinsona** [comment]
@SpecialKelsey added the new training image - let me know if you are good with all these images

**Comment by SpecialKelsey** [comment]
@sinkinsona 
All good.  I'll have the boss give me his OK and then I'll close this issue.

**Comment by SpecialKelsey** [comment]
@sinkinsona 
All good.
