### ISSUE TITLE
images about us

### ISSUE THREAD

**Issue by sinkinsona** [Sabytel-Web/sabytel#42]
Create and drag and drop into this issue about us image
http://sabytel.com/demo/about-us.php

**Comment by SpecialKelsey** [comment]
@sinkinsona @ahmedhussein 
Banner image About page = AdobeStock_95169113.jpeg
About page – Who we are = volumetric_01.jpg (not on Ahmed One drive) he will need to add it

**Comment by sinkinsona** [comment]
Removed the banner image to make all banners the same across the site and added the requested image.  Let me know what you think

**Comment by SpecialKelsey** [comment]
@sinkinsona 
All good.  consider this one done.

**Comment by sinkinsona** [comment]
closing the issue
