### ISSUE TITLE
image - what we can do for you

### ISSUE THREAD

**Issue by sinkinsona** [Sabytel-Web/sabytel#43]
Create and drag and drop into this issue image for what we can do for you 
http://sabytel.com/demo/what-we-can-do.php

**Comment by SpecialKelsey** [comment]
@sinkinsona @ahmedhussein 
This is the image I want.

![adobestock_94644195_wm](https://cloud.githubusercontent.com/assets/16320855/15405713/04ba5006-1dd1-11e6-94fa-8f39a33d7994.jpeg)
[What we can do for you image.docx](https://github.com/Sabytel-Web/sabytel/files/273244/What.we.can.do.for.you.image.docx)

**Comment by SpecialKelsey** [comment]
@sinkinsona @ahmedhussein 
Change of heart.  I'll use this one on the About Us banner
Let's use =AdobeStock_95169113.jpeg

**Comment by sinkinsona** [comment]
added the requested image - have a look and let me know

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Since there is no longer a banner image on the About Us page this one is no longer required. As far as I know Ahmed has not purchased it either.  I'm waiting on a response from him.  If he did purchase it, we can use it on the Slider images.

**Comment by sinkinsona** [comment]
Added a new image that we are able to use - let me know what you think

**Comment by SpecialKelsey** [comment]
@sinkinsona 
All good.  I can't close or re-open issues.  Don't know if it has to do with my profile.
