### ISSUE TITLE
select icons for you need us page

### ISSUE THREAD

**Issue by sinkinsona** [Sabytel-Web/sabytel#44]
Icons can be found as part of the template
http://sabytel.com/demo/you-need-us.php

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Project Initiation = eye (the one that is there now)
After Design, before implementation = checkmark (the one that is there now)
After Implementation, before Rollout = rocket (the one that is there now)
After rollout - thumbs up (from the Web Apps icon)
When your organization....= double arrow (the one that is there now)
When you don't know you clients....= User + (from the Web Apps icon)

**Comment by sinkinsona** [comment]
Added the new icons
