### ISSUE TITLE
Icon Cyber and ICT Security

### ISSUE THREAD

**Issue by sinkinsona** [Sabytel-Web/sabytel#45]
Select icons for this page
http://sabytel.com/demo/cyber-ict-security.php

**Comment by SpecialKelsey** [comment]
@sinkinsona 
These are all from the Web Applications Icons list
Certification to Information Security Management Systems (ISMS) = certificate
Threat and Risk Assessment and Implementation = umbrella
Risk Management = bomb
Business Continuity Plan (BCP) = life ring
Disaster Recovery Plan (DRP) = road
Vulnerability Assessment (VA)/ Penetration Testing (Pen Test) = user secret
Incident Handling = shield
Cloud computing = cloud
Identity Management Solution (IMS) = Users
SCADA (Supervisory Control And Data Acquisition) and Internet of Things = puzzle piece
Security Research & Development = pencil-square-o
Data Security = database
Individual Security Documentation = book

**Comment by sinkinsona** [comment]
added the requested icons
