### ISSUE TITLE
images - Physical security Solution

### ISSUE THREAD

**Issue by sinkinsona** [Sabytel-Web/sabytel#46]
drag and drop images into this issue for this slider on this page
http://sabytel.com/demo/physical-security-solutions.php

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Nabil is not certain if we will keep this page.  So for now we will use only two images for the carousel. 
Ahmed still has to find one, and the other will be the Sabytel logo.
MetalLogoMockup_V2.jpg
the other is 
![anti_intrusion](https://cloud.githubusercontent.com/assets/16320855/16654216/c09e6114-4422-11e6-8337-68fa0a7e50da.jpg)

**Comment by sinkinsona** [comment]
added some sample images -  let me know what you think

**Comment by SpecialKelsey** [comment]
@sinkinsona 
I like the image you chose.  Keep it that way as long as there are no royalties for those images.  If it's all good for that, consider this one done.

**Comment by sinkinsona** [comment]
Added new images that are license free - let me know what you think

**Comment by SpecialKelsey** [comment]
@sinkinsona 
All good.  Can't close this issue.  No button for it.
