### ISSUE TITLE
Icons - Physical security Solution

### ISSUE THREAD

**Issue by sinkinsona** [Sabytel-Web/sabytel#47]
Select icons for this page
http://sabytel.com/demo/physical-security-solutions.php

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Access control = ET Lock
Camera Surveillance - ET Camera
Barriers & Turnstiles = ET Caution
Sophisticated Intrusion Detection System = ET Laptop
Customised Electronic Module Design - ET Genius

**Comment by sinkinsona** [comment]
added requested icons
