### ISSUE TITLE
Cyber and ICT Security

### ISSUE THREAD

**Issue by SpecialKelsey** [Sabytel-Web/sabytel#50]
@sinkinsona 
Hi Andrew,
I thought the page should look like the attached document and that the icons would open the page with the text.  I didn't expect the whole description to be at the bottom of the page.

[Final-New Sabytel Cyber Security-Services mock up.docx](https://github.com/Sabytel-Web/sabytel/files/273312/Final-New.Sabytel.Cyber.Security-Services.mock.up.docx)

**Comment by sinkinsona** [comment]
@SpecialKelsey I did not realize that you wanted the text to be in a separate window.  Have a look at this page http://sabytel.com/demo/cyber-ict-security.php and click on Certification to Information Management Systems (ISMS) and let me know if this approach works for you?  If you like it I can make the rest of them work like that.  Let me know

**Comment by SpecialKelsey** [comment]
@sinkinsona 
HI Andrew,
I like that approach better.  The original smarty design had the Icons on the top of the page and Features that we have now made into the You need Us was on the bottom of the page.  Is there any way to make it look  like the original Smarty page and have the icons on the top part and the icons for the You need Us  part work the way you designed it for the ISMS icon.
![smarty services layout 2](https://cloud.githubusercontent.com/assets/16320855/16231049/5dc3a672-3792-11e6-9ffb-bae721570cab.jpg)

**Comment by sinkinsona** [comment]
I am not sure that I understand - Should I not do the pop up window anymore?  What happens when you click on the icons?  Considering that we only have 5 pages do we really want 2 of theme to look the same?

**Comment by SpecialKelsey** [comment]
Hi Andrew,

 

Yes we keep the pop ups.  As for the layout of the page, Smarty Services Layout 2 is what we had selected.  The top had the icons for the different Cyber/ICT services we offer and the bottom was to have the Sabytel Logo with the You need Us information.  I had chosen that page because I was under the impression the You Need Us would reside with the Cyber/ICT Services and not under the About Us menu. The mock up below is what I had envisioned.   If this is not clear we can discuss via Skype at your convenience.

 

 

New Sabytel – Cyber Security Menu (Services icon from Landing Page)









 

 

Elise Kelsey 

Client Relationship Manager / Gestionnaire des relations clients

Email :  <mailto:elise@sabytel.com> elise@sabytel.com

Web :  <http://www.sabytel.com/> www.sabytel.com 

 

Tel : + 1-613-235-9999

Cell :  +1-613-299-3459

**Comment by sinkinsona** [comment]
@SpecialKelsey have a look and let me know if you are good with what has been implemented
http://sabytel.com/demo/cyber-ict-security.php

**Comment by SpecialKelsey** [comment]
@sinkinsona 
it's perfect.  That's what I was looking for.  Great work

**Comment by SpecialKelsey** [comment]
@sinkinsona 
I can't reopen but since we have a few minor changes I thought I'd just add it here.  I can't login to Google docs either, so here it is

Text for the Cyber and IT Services - minor change
[Cyber and ICT Security Services What We Do Only-Revised 2016-08-25.docx](https://github.com/Sabytel-Web/sabytel/files/437651/Cyber.and.ICT.Security.Services.What.We.Do.Only-Revised.2016-08-25.docx)

Cyber and ICT Security Services What We Do 

ISO Certification to Information Security Management Systems (ISMS)

Information Security Management Systems (ISMS) is a systematic approach to managing sensitive company information so that it remains secure. It includes people, processes and IT systems by applying a risk management process.

Sabytel certified ISO/IEC 27001 Lead Auditor staff will assist your organization to implement and abet you to become certified ensuring your organization benefits from the best practice it contains. ISO/IEC 27001 can help small, medium and large businesses in any sector keep information assets secure therefore reassuring your customer and your clients.

+  Add ISO in front of Certification……for the icon
 
If it’s too long can you make it
ISO Certification-Information Security Management Systems (ISMS)

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Got Google docs to work,

https://drive.google.com/open?id=0B95j4zfm5LiLSWw0czU4VTVzOG8

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Some more changes to the Cyber and ICT Security.  We need to add a new icon and text for IT Architecture- I will open in a separate issue.  

To be able to accommodate that new item and not disrupt the look, I decided to combine the Risk Management with the Threat & Risk Assessment and Implementation and we keep the bomb for the icon.  See the revised text in google docs - https://drive.google.com/open?id=0B95j4zfm5LiLX2FPSlVsM0hWSDQ
Hope you can fit the title under the Icon

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Here is the IT Security Architecture Design & Implementation document to add to the Cyber and ICT Security on the top of the page with the other Icons. https://drive.google.com/file/d/0B95j4zfm5LiLY1VydloxTjBYbkk/view?usp=sharing
I don't remember how to find the icons so I put the image of what I would like.

**Comment by sinkinsona** [comment]
Implemented the requested fixes - icons can be found here http://fontawesome.io/icons/

re-open if other changes are required

**Comment by SpecialKelsey** [comment]
@sinkinsona 

Nabil would like another small change.  THe title under the icon for ISO Certification to Information Security Management Systems (ISMS) should be ISO 27001 Certification to Information Security Management Systems (ISMS).  Hope this still fits

**Comment by sinkinsona** [comment]
Added the requested change - if others are need just **re-open** the issue

**Comment by SpecialKelsey** [comment]
Hi Andrew,  

 

There is no option for me to re-open issues.  Don’t know if it has to do with my permissions.  

 

Elise Kelsey 

Client Relationship Manager / Gestionnaire des relations clients

Email :  <mailto:elise@sabytel.com> elise@sabytel.com

Web :  <http://www.sabytel.com/> www.sabytel.com 

 

Tel : 613-299-3459

Sabytel :  613-235-9999

Fax : 343-887-9388
