### ISSUE TITLE
Content - Pay Pal setup

### ISSUE THREAD

**Issue by SpecialKelsey** [Sabytel-Web/sabytel#51]
@sinkinsona 
Is it possible to have a page so people can pay via PayPal.  Please let me know. If this is too much, we make it for an update a little further down the road.

**Comment by sinkinsona** [comment]
In order to implement Paypal I would need you to create a premium account which does not cost anything + let me know the products and prices of services that we would like to sell.  Let me know if you would like to discuss further

**Comment by sinkinsona** [comment]
Spoke to Nabil about this one and seems he has found a solution via email that can be used.  Closing this issue for now and can re-open if we want to relook at this later
