### ISSUE TITLE
Content and Layout

### ISSUE THREAD

**Issue by SpecialKelsey** [Sabytel-Web/sabytel#52]
@sinkinsona 
A change in the text on the landing page under the top images 
Change the text under 'We understand.....' from 'we give you the tools.....' to this new text.

We see information security as an enabler and that sets us apart from other Cyber Security companies. We don’t tell you what you can’t do. We tell you how you can operate your business securely.

https://drive.google.com/file/d/0B95j4zfm5LiLQXNjUEtTU09hMGM/view?usp=sharing

**Comment by sinkinsona** [comment]
I have made the requested change - closing this issue
