### ISSUE TITLE
ISO Training - Hyperlink

### ISSUE THREAD

**Issue by SpecialKelsey** [Sabytel-Web/sabytel#53]
@sinkinsona 
Hi Andrew.  We need to have a hyperlink for the ISO Training that brings us to the Niskaa website.  It would need to open in a new tab so people don't loose the Sabytel website.  Maybe add a message that they will be redirected to another website when clicking.  

Can this link be added to the ISO Training feature on the landing page.  Please advise.

**Comment by sinkinsona** [comment]
I added a button on the homepage but wondering if we need a call to action.  Something more visible&

**Comment by SpecialKelsey** [comment]
@sinkinsona 
All good.
