### ISSUE TITLE
Go Live

### ISSUE THREAD

**Issue by SpecialKelsey** [Sabytel-Web/sabytel#54]
@Sabytel-Web/sabytel_team 
Hi Andrew,

We are just about done with everything,  I'd like to go live no later than Friday, October 7th.  Please advise of the possibility.  We can fix the little issues, if any, after that.

**Comment by sinkinsona** [comment]
If I could have up to Oct 11 to make it live that would work best for me as I am not around this weekend and still want to make minor tweaks.  Let me know

**Comment by SpecialKelsey** [comment]
@sinkinsona 
That would work for me.  I'm on vacation after that from Oct 12th to the 28th.

**Comment by sinkinsona** [comment]
Site has been published as of last night.
