### ISSUE TITLE
Services page content & layout

### ISSUE THREAD

**Issue by SpecialKelsey** [Sabytel-Web/sabytel#8]
@sinkinsona, @Sabytel @ahmedhussein 
Services: 
 Cyber and ICT Security - What we do 
 Physical Security: Security Systems tailored to your needs

If the Smarty layout 2 is chosen for the Services page, here are my suggestions. 
 When you click on the icon, it would be direct you to the text of each solution These are all part of the Cyber and ICT Security Services What We Do document

The top part where the icons are would be broken down into: 
 Security Research & Development
 Data Security
 Individual Security Documentation
 Cloud computing 
 Business Continuity/ Disaster Recovery Plan
 Risk Management
 Identity Management Solution (IMS)
 Vulnerability Assessment (VA)/ Penetration Testing 
 Incident Handling
 Certification to Information Security Management Systems (ISMS)

The titles may change a little bit because some are quite long. My view would be for the icons and the text under the icon:
 Security for the Icon and the text: Encryption, intrusion detection and anti-malware
 Data Security for the Icon and the text: Protection, guidance and tools
 Security Documentation for the Icon and the text: IT Security plan, process and solutions
 Cloud computing for the Icon and the text: Efficient and secure solutions
 Disaster Recovery for the Icon and the text: Business continuity protection
 Risk Management for the Icon and the text: Effectively mitigate security risks
 Identity Management for the Icon and the text: Identify, implement and manage solutions
 Vulnerability for the Icon and the text: Prevent weaknesses and exposures
 Incident Handling for the Icon and the text: Limit crisis, emergencies or disaster
 Certification for the Icon and the text: Information Security Management Systems and ISO training.

For the bottom part of the page for Services, the Smarty apps shows a telephone with icons and little blurb of text. So same concept as the top part but change the phone picture to something that relates to Physical Security and remove the text and just have text for the Icon. The text for the icon is found on the document Security Systems tailored to your needs 

Access Control
 Identification Systems
 Intrusion detection
 Electronic modules
 Computer infrastructure
 Identification card production
 Customer Service

I also need to work on the text for Why Choose Us that is displayed at the bottom of the page.

Thoughts, comments, suggestion are always welcome.

**Comment by SpecialKelsey** [comment]
@sinkinsona . @ahmedhussein , @Sabytel 

Here is a very quick mark up of what I think the Services page should look like. 

New Sabytel-Services Web Page.docx

**Comment by sinkinsona** [comment]
@SpecialKelsey thanks for the mock as it really helps show how you would like the Service page to look.  I also like that you put all the services page content discussion in a seperate issue as it makes it easier to implement.

![image](https://cloud.githubusercontent.com/assets/1258144/12121776/202917b4-b3a5-11e5-8318-e98aeece8b74.png)

**Comment by SpecialKelsey** [comment]
@sinkinsona, @ahmedhussein, @Sabytel 
Here is what I propose for the Home Page
New Sabytel-Home Page

Top Image:  Welcome to Sabytel Technologies Inc.
Cyber and ICT Security services at its best 
or
Cyber and ICT Security is our main expertise

2nd Image (if any) Awareness of the risks and available safeguards is the first line of defense for the security of information systems and networks.

Sabytel – Where your security matters.

Middle of page – 4 images + text
4 areas of expertise


1.	Today’s business environment is changing and you need to change with it. A bigger Business to Business (B2B) internet presence would go a long way towards reducing your cost of doing business while increasing your bottom line and keeping you competitive. 
How can you securely increase your E-Business while every day, more and more major corporations are being hacked and penetrated by cybercriminals, corporate spies and dedicated hacktivists? How can you be more open to the electronic age while better protecting yourself at the same time?
You need to protect yourself and the right Information Security plan can help. Sabytel provides the experience, knowledge and tools you need to enable your business to process safely and securely while you expand your internet presence. 

2.	Security awareness is the knowledge and attitude members of an organization possess regarding the protection of the physical and information assets.

Being security aware means you understand that there is the potential for some people to deliberately or accidentally steal, damage, or misuse the data that is stored within your organizations’ computer systems. It is prudent to support the assets of the institution’s information, physical and personal, by stopping that from happening.

3.	Sabytel offers specialized IT security services that address your organization’s particular needs. 

Threat and Risk Assessments We conduct full IT threat and Risk Assessments providing recommendations for security improvements. 

Network Vulnerability Assessments We provide full network vulnerability assessments culminating in reports on identified vulnerabilities and step-by-step plans on how to eliminate them. 

Departmental Policies and Procedures We help you to develop policies and procedures to improve your IT network security. 

Business Resumption Plan (BRP) We assist you in developing procedures and schedule to test your BRP on an annual basis.  This will include documentation of critical business functions that need to be recovered in order for business operations to continue.

Certification and Accreditation: Conducts the full Certification and Accreditation activities ensuring successful certification and accreditation of your systems in accordance with defined national and international requirements.

4.	Corporate Strategy Solution will help your organization identify and address strategic issues 

Sabytel can help to improve your organization’s business operations by developing a Corporate Strategy Solution that will help your organization to identify and address strategic issues that are important to its success. As part of this solution, Sabytel will provide a two-part strategic analysis of your organization, including a Base Case Analysis of current operations, and a Strategy Formulation and Implementation plan to improve upon those operations. The Market Research Studies solution will provide you with reliable information that can be used to identify your organization’s market niche and develop effective business strategies

Also here is a quick mock up

[New Sabytel-Home Page mock up.docx](https://github.com/Sabytel-Web/sabytel/files/78882/New.Sabytel-Home.Page.mock.up.docx)

**Comment by sinkinsona** [comment]
layout:  page-services-2.html

**Comment by sinkinsona** [comment]
Replaced with https://github.com/Sabytel-Web/sabytel/issues/19
