### ISSUE TITLE
Create Demo site

### ISSUE THREAD

**Issue by sinkinsona** [Sabytel-Web/sabytel#9]
Create a demo site where the team can review progress being made.

**Comment by sinkinsona** [comment]
@Sabytel @ahmedhussein @SpecialKelsey 
Still very much a work in progress but is the demo new Sabytel site
http://sabytel.com/demo/

I will continue to keep it updated as we make further progress

**Comment by SpecialKelsey** [comment]
@sinkinsona 
Nice work. :+1:  It's helps to put things in perspective with the demo version.  Tells me I still have a lot of work to do.

**Comment by sinkinsona** [comment]
closed
